from flask import Blueprint, request, jsonify

import logging
from datetime import datetime

print_bp = Blueprint('print', __name__)

def format_receipt(data):
    # Helper to center text
    def center(text, width=32):
        if not text: return " " * width
        if len(text) >= width:
            return text[:width]
        spaces = (width - len(text)) // 2
        return " " * spaces + text

    # Helper for lines
    def line(char='-', width=32):
        return char * width

    # Basic POS58 width is usually 32 characters for normal font
    WIDTH = 32
    
    lines = []
    
    # ESC/POS Commands
    ESC = '\x1b'
    GS = '\x1d'
    RESET = ESC + '@'
    BOLD_ON = ESC + 'E' + '\x01'
    BOLD_OFF = ESC + 'E' + '\x00'
    CENTER = ESC + 'a' + '\x01'
    LEFT = ESC + 'a' + '\x00'
    
    # Initialize
    lines.append(RESET)
    
    # Header
    lines.append(CENTER)
    lines.append(BOLD_ON + "JUAN AI" + BOLD_OFF + "\n")
    lines.append("AI-Powered Health Assessment\n")
    now = datetime.now()
    lines.append(now.strftime("%b %d, %Y %I:%M %p") + "\n")
    lines.append(line('=') + "\n")
    
    # Patient Info
    lines.append(LEFT)
    lines.append(BOLD_ON + "PATIENT INFORMATION" + BOLD_OFF + "\n")
    lines.append(f"Name: {data.get('firstName', 'N/A')} {data.get('lastName', '')}\n")
    lines.append(f"Age: {data.get('age', 'N/A')} years\n")
    lines.append(f"Gender: {data.get('sex', 'N/A')}\n")
    lines.append(f"BMI: {data.get('bmi', 'N/A')} ({data.get('bmiCategory', 'N/A')})\n")
    lines.append(line('-') + "\n")
    
    # Vitals
    lines.append(BOLD_ON + "VITAL SIGNS" + BOLD_OFF + "\n")
    
    checklist = data.get('checklist', [])
    
    # Temp
    if 'bodytemp' in checklist or data.get('temperature'):
        lines.append(f"Body Temp: {data.get('temperature', 'N/A')} C\n")
        lines.append(f"Status: {data.get('temperatureStatus', 'N/A')}\n")
        
    # Heart/SpO2
    if 'max30102' in checklist or data.get('heartRate'):
        lines.append(f"Heart Rate: {data.get('heartRate', 'N/A')} BPM\n")
        lines.append(f"Status: {data.get('heartRateStatus', 'N/A')}\n")
        lines.append(f"SpO2: {data.get('spo2', 'N/A')}%\n")
        lines.append(f"Status: {data.get('spo2Status', 'N/A')}\n")
        lines.append(f"Resp. Rate: {data.get('respiratoryRate', 'N/A')}/min\n")
        lines.append(f"Status: {data.get('respiratoryStatus', 'N/A')}\n")

    # BP
    if 'bloodpressure' in checklist or data.get('systolic'):
        lines.append(f"BP: {data.get('systolic', 'N/A')}/{data.get('diastolic', 'N/A')} mmHg\n")
        lines.append(f"Status: {data.get('bloodPressureStatus', 'N/A')}\n")
        
    # Weight/Height
    if 'bmi' in checklist or data.get('weight'):
        lines.append(f"Weight: {data.get('weight', 'N/A')} kg\n")
        lines.append(f"Height: {data.get('height', 'N/A')} cm\n")
        
    lines.append(line('-') + "\n")
    
    # Risk
    lines.append(BOLD_ON + "AI RISK ASSESSMENT" + BOLD_OFF + "\n")
    lines.append(f"Risk Level: {data.get('riskLevel', 0)}%\n")
    lines.append(f"Category: {data.get('riskCategory', 'N/A')}\n")
    lines.append(line('-') + "\n")
    
    # Recommendations (Medical Actions)
    if data.get('suggestions'):
        lines.append(BOLD_ON + "SUGGESTED ACTIONS" + BOLD_OFF + "\n")
        for i, item in enumerate(data.get('suggestions', [])):
            lines.append(f"- {item}\n")
        lines.append("\n")

    # Preventive Strategies
    if data.get('preventions'):
        lines.append(BOLD_ON + "PREVENTIVE STRATEGIES" + BOLD_OFF + "\n")
        for i, item in enumerate(data.get('preventions', [])):
            lines.append(f"- {item}\n")
        lines.append("\n")

    # Wellness Tips
    if data.get('wellnessTips'):
        lines.append(BOLD_ON + "WELLNESS TIPS" + BOLD_OFF + "\n")
        for i, item in enumerate(data.get('wellnessTips', [])):
            lines.append(f"- {item}\n")
        lines.append("\n")

    # Provider Guidance
    if data.get('providerGuidance'):
        lines.append(BOLD_ON + "PROVIDER GUIDANCE" + BOLD_OFF + "\n")
        for i, item in enumerate(data.get('providerGuidance', [])):
            lines.append(f"{item}\n")
        lines.append("\n")

    lines.append(line('=') + "\n")
    lines.append(CENTER)
    lines.append("*** IMPORTANT DISCLAIMER ***\n")
    lines.append("This AI health assessment is for\n")
    lines.append("informational purposes only.\n")
    lines.append("Consult a doctor for medical advice.\n")
    lines.append("\nGenerated by Juan AI\n")
    lines.append(f"Report ID: HG{str(int(datetime.now().timestamp()))[-6:]}\n")
    lines.append("\n\n\n\n") # Feed
    
    return "".join(lines)

@print_bp.route('/receipt', methods=['POST'])
def print_receipt():
    try:
        import win32print  # Import here to avoid global side effects
        
        data = request.json
        if not data:
            return jsonify({'error': 'No data provided'}), 400
            
        receipt_text = format_receipt(data)
        
        printer_name = win32print.GetDefaultPrinter()
        if not printer_name:
             return jsonify({'error': 'No default printer found'}), 500

        hPrinter = win32print.OpenPrinter(printer_name)
        try:
            hJob = win32print.StartDocPrinter(hPrinter, 1, ("Health Receipt", None, "RAW"))
            try:
                win32print.StartPagePrinter(hPrinter)
                # Send bytes. cp437 is standard for POS printers.
                win32print.WritePrinter(hPrinter, receipt_text.encode('cp437', errors='ignore'))
                win32print.EndPagePrinter(hPrinter)
            finally:
                win32print.EndDocPrinter(hPrinter)
        finally:
            win32print.ClosePrinter(hPrinter)
            
        return jsonify({'success': True, 'message': 'Printed successfully'})
    except Exception as e:
        logging.error(f"Print failed: {e}")
        return jsonify({'error': str(e)}), 500

@print_bp.route('/status', methods=['GET'])
def check_printer_status():
    try:
        import win32print

        printer_name = win32print.GetDefaultPrinter()
        if not printer_name:
            return jsonify({'status': 'error', 'message': 'No default printer found'}), 404

        hPrinter = win32print.OpenPrinter(printer_name)
        try:
            # Level 2 gives us the status attributes
            printer_info = win32print.GetPrinter(hPrinter, 2)
            status_code = printer_info['Status']
            
            # Status Flags
            PRINTER_STATUS_ERROR = 0x00000002
            PRINTER_STATUS_PAPER_JAM = 0x00000008
            PRINTER_STATUS_PAPER_OUT = 0x00000010
            PRINTER_STATUS_PAPER_PROBLEM = 0x00000040
            PRINTER_STATUS_OFFLINE = 0x00000080
            PRINTER_STATUS_OUTPUT_BIN_FULL = 0x00000800
            PRINTER_STATUS_NOT_AVAILABLE = 0x00001000
            PRINTER_STATUS_DOOR_OPEN = 0x00400000
            
            status_messages = []
            status = 'ready'
            
            if status_code & PRINTER_STATUS_ERROR:
                status_messages.append("Error")
                status = 'error'
            if status_code & PRINTER_STATUS_PAPER_JAM:
                status_messages.append("Paper Jam")
                status = 'error'
            if status_code & PRINTER_STATUS_PAPER_OUT:
                status_messages.append("Paper Out")
                status = 'warning'
            if status_code & PRINTER_STATUS_PAPER_PROBLEM:
                status_messages.append("Paper Problem")
                status = 'error'
            if status_code & PRINTER_STATUS_OFFLINE:
                status_messages.append("Offline")
                status = 'error'
            if status_code & PRINTER_STATUS_OUTPUT_BIN_FULL:
                status_messages.append("Bin Full")
                status = 'warning'
            if status_code & PRINTER_STATUS_NOT_AVAILABLE:
                status_messages.append("Not Available")
                status = 'error'
            if status_code & PRINTER_STATUS_DOOR_OPEN:
                status_messages.append("Door Open")
                status = 'error'
                
            if not status_messages:
                # Sometimes status is 0 meaning ready, or just small unrelated flags
                message = "Ready"
            else:
                message = ", ".join(status_messages)
                
            return jsonify({
                'status': status,
                'message': message,
                'printer_name': printer_name,
                'status_code': status_code
            })
            
        finally:
            win32print.ClosePrinter(hPrinter)
            
    except Exception as e:
        logging.error(f"Printer status check failed: {e}")
        return jsonify({'status': 'error', 'message': str(e)}), 500
