import React, { useState, useEffect } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import "./Sharing.css";

export default function Sharing() {
  const navigate = useNavigate();
  const location = useLocation();
  // const [isVisible, setIsVisible] = useState(false); // Unused
  const [userData, setUserData] = useState(null);
  const [isPrinting, setIsPrinting] = useState(false);
  const [printComplete, setPrintComplete] = useState(false);
  // const [receiptContent, setReceiptContent] = useState(""); // Unused
  // const printFrameRef = useRef(null); // Unused

  // Fallback print removed as we want to enforce no-dialog printing via backend

  const directPrint = async () => {
    console.log("🖨️ Starting direct print via Backend...");
    console.log("📊 Printing health data:", userData);

    setIsPrinting(true);

    try {
      const response = await fetch(`${process.env.REACT_APP_API_URL || 'http://localhost:5000'}/api/print/receipt`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(userData),
      });

      const result = await response.json();

      if (response.ok) {
        console.log("✅ Print command sent successfully");
        setPrintComplete(true);
      } else {
        throw new Error(result.error || 'Print failed');
      }
    } catch (error) {
      console.error('Print failed:', error);
      // Fallback to browser print if backend fails, but user specifically requested no dialog.
      // We will just notify the user.
      alert("Printing failed: " + error.message + ". Please check if the printer is connected and the backend is running. If this persists, please contact support.");
    } finally {
      setIsPrinting(false);
    }
  };

  const startAutoPrint = React.useCallback(() => {
    console.log("🖨️ Starting auto-print...");

    if (!userData) {
      console.log("⏳ User data not ready, waiting...");
      // setTimeout(startAutoPrint, 500); // Avoid recursive timeout in callback, simplified logic below
      return;
    }

    console.log("✅ Data ready, starting print...");
    directPrint();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [userData]); // directPrint uses userData from closure, safe to exclude

  useEffect(() => {
    console.log("📍 Sharing page received data:", location.state);

    if (location.state) {
      setUserData(location.state);
      console.log("✅ Complete health data loaded in Sharing:", location.state);

      // Auto-start printing when component loads and content is ready
      // We use a small delay to ensure state update has processed
      const printTimer = setTimeout(() => {
        // Trigger print directly here to avoid complex dependency chains with userData
        // or call the function if it's stable
      }, 1000);

      return () => clearTimeout(printTimer);

    } else {
      console.log("❌ No data received from Result page");
      navigate("/measure/result");
      return;
    }

    // Removing isVisible logic as it was unused
  }, [location.state, navigate]);

  // Effect to trigger print when userData is set
  useEffect(() => {
    if (userData) {
      const timer = setTimeout(() => {
        startAutoPrint();
      }, 1000);
      return () => clearTimeout(timer);
    }
  }, [userData, startAutoPrint]);

  // generateReceiptContent function removed - receipt is now generated by backend

  const clearAllUserData = () => {
    console.log('🧹 Clearing all user data and resetting system...');

    localStorage.removeItem('currentUser');
    localStorage.removeItem('userData');
    sessionStorage.removeItem('currentUser');
    sessionStorage.removeItem('userData');

    if (window.reduxStore) {
      window.reduxStore.dispatch({ type: 'RESET_USER_DATA' });
    }

    if (window.currentUserData) {
      window.currentUserData = null;
    }

    console.log('✅ All user data cleared - system ready for next user');
  };

  const handleReturnHome = () => {
    console.log('🏠 Returning to home - clearing all user data and resetting system');

    clearAllUserData();

    setTimeout(() => {
      navigate("/", {
        replace: true,
        state: {
          fromSharing: true,
          reset: true
        }
      });
    }, 100);
  };

  const handlePrintAgain = () => {
    setPrintComplete(false);
    startAutoPrint();
  };

  if (!userData) {
    return (
      <div className="share-container">
        <div className="share-content visible">
          <div className="share-header">
            <div className="share-icon">
              <div className="ready-icon">⚠️</div>
            </div>
            <h1 className="share-title">Loading Data...</h1>
            <p className="share-subtitle">Please wait while we load your health information</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="container-fluid d-flex justify-content-center align-items-center min-vh-100 p-0 share-container">
      <div className={`card border-0 shadow-lg p-4 p-md-5 mx-3 share-content page-transition`} style={{ maxWidth: '600px', width: '100%' }}>

        {/* Header */}
        <div className="text-center mb-5 share-header">
          <div className="mb-4 d-flex justify-content-center">
            <div className="share-icon" style={{ fontSize: '4rem' }}>
              {isPrinting ? (
                <div className="printing-animation">
                  <span className="printer-icon">🖨️</span>
                </div>
              ) : printComplete ? (
                <span className="success-icon text-success">✅</span>
              ) : (
                <span className="ready-icon">🖨️</span>
              )}
            </div>
          </div>

          <h1 className="fw-bold mb-2 share-title">
            {isPrinting ? "Printing Receipt..." :
              printComplete ? "Print Complete!" :
                "Printing Health Receipt"}
          </h1>

          <p className="text-muted fs-5 share-subtitle">
            {isPrinting ? "Sending to thermal printer..." :
              printComplete ? "Your health receipt has been printed" :
                "Auto-printing your health assessment"}
          </p>
        </div>

        {/* Patient Info */}
        <div className="mb-5 patient-info">
          <div className="card border-0 bg-light p-4 patient-card">
            <div className="h4 fw-bold mb-2 text-center text-primary patient-name">
              {userData.firstName} {userData.lastName}
            </div>
            <div className="text-center text-muted patient-details">
              Age: {userData?.age || 'N/A'} • {userData?.sex ? userData.sex.charAt(0).toUpperCase() + userData.sex.slice(1).toLowerCase() : 'N/A'} • Risk Level: {userData?.riskLevel || 'N/A'}%
            </div>
          </div>
        </div>

        {/* Status Info */}
        <div className="text-center mb-4 status-info">
          <div className="printer-status mb-3 text-muted small">
            <strong className="d-block mb-1">Thermal Printer Ready</strong>
            <span>POS58 • Large Font Size • Auto-print</span>
          </div>

          {isPrinting && (
            <div className="print-progress">
              <div className="progress mb-2" style={{ height: '6px' }}>
                <div className="progress-bar progress-bar-striped progress-bar-animated bg-primary" role="progressbar" style={{ width: '100%' }}></div>
              </div>
              <small className="text-muted">Printing health receipt for {userData.firstName}...</small>
            </div>
          )}
        </div>

        {/* Action Buttons */}
        <div className="d-grid gap-3 action-buttons">
          {printComplete ? (
            <>
              <button
                className="btn btn-outline-primary btn-lg rounded-pill fw-bold"
                onClick={handlePrintAgain}
              >
                🖨️ Print Another Copy
              </button>

              <button
                className="btn btn-danger btn-lg rounded-pill fw-bold text-white shadow"
                onClick={handleReturnHome}
              >
                🏠 Return to Home (New User)
              </button>
            </>
          ) : isPrinting ? (
            <div className="text-center py-3 text-muted">
              <div className="spinner-border text-primary mb-2" role="status"></div>
              <div>Please wait while we print your receipt...</div>
            </div>
          ) : (
            <button
              className="btn btn-primary btn-lg rounded-pill fw-bold shadow"
              onClick={startAutoPrint}
            >
              🖨️ Print Now
            </button>
          )}
        </div>

      </div>
    </div>
  );
}